[general]
import = ["~/.config/alacritty/colors.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/bin/fish"

[window]
dynamic_title = false
opacity = 0.92
title = "Alacritty"
dimensions = { columns = 40, lines = 16 }

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

